config/routes.rb
Rails.application.routes.draw do

  namespace :admins do
    get 'cats/index'
    get 'cats/show'
  end
  namespace :admins do
    get 'users/index'
    get 'users/show'
    get 'users/update'
    get 'users/destroy'
  end
  get 'inquiry_rooms/show'
  root 'home#home'
  get  'about' => 'home#about'
  get  'aboutcat' => 'home#aboutcat'

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    resources :users do
      resources :inquiry_rooms
    end
    resources :cats do
      resources :cat_images
      resource :favorites, only: [:create, :destroy]
    end
    resources :rooms

    namespace :admins do
    resources :users
    resources :cats
    resources :inquiry_rooms
  end

    resources :admins do
      collection do
        get :home
    end
  end

#actioncable
mount ActionCable.server => '/cable'

end

app/views/admins/home.html.erb
 <div class="container">
	<div class="row">
	<div class="d-inline-block col-lg-8 col-lg-offset-2" style="margin-top: 50px;">
      <div class="block-center">
		 <%= link_to "会員一覧", admins_users_path, class: "btn btn-secondary col-md-3", :style=>"background-color: #777;color: white;margin: 10px 10px 10px 10px;" %>

		 <%= link_to "猫一覧", admins_cats_path, class: "btn btn-secondary col-md-3", :style=>"background-color: #777;color: white;margin: 10px 10px 10px 10px;" %>

		 <%= link_to "お問い合わせ一覧", admins_inquiry_rooms_path, class: "btn btn-secondary col-md-3", :style=>"background-color: #777;color: white;margin: 10px 10px 10px 10px;" %>
	  </div>
    </div>
    </div>
</div>