config/routes.rb
Rails.application.routes.draw do

  namespace :admins do
    get 'cats/index'
    get 'cats/show'
  end
  namespace :admins do
    get 'users/index'
    get 'users/show'
    get 'users/update'
    get 'users/destroy'
  end
  get 'inquiry_rooms/show'
  root 'home#home'
  get  'about' => 'home#about'
  get  'aboutcat' => 'home#aboutcat'

  devise_for :admins, controllers: {
  sessions:      'admins/sessions',
  passwords:     'admins/passwords',
  registrations: 'admins/registrations'
}
devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    resources :users do
      resources :inquiry_rooms
    end
    resources :cats do
      resources :cat_images
      resource :favorites, only: [:create, :destroy]
    end
    resources :rooms

    namespace :admins do
    resources :users
    resources :cats
    resources :inquiry_rooms
  end

    resources :admins do
      collection do
        get :home
    end
  end

#actioncable
mount ActionCable.server => '/cable'

end

app/models/inquiry_message.rb
class InquiryMessage < ApplicationRecord

	belongs_to :inquiry_room

	# Scopes
	default_scope -> {order(created_at: :asc)}

	# Validations
	validates :inquiry_room_id, presence: true
	validates :content, presence: true, length: {maximum: 500}
	validates :adminflag, presence: true

	# Callbacks
	after_create_commit { InquiryMessageBroadcastJob.perform_later self }

	# Methods
	def Message.recent_in_inquiry_room(inquiry_room_id)
	  where(inquiry_room_id: inquiry_room_id).last(500)
	end

end

app/views/inquiry_messages/_inquiry_message.html.erb
 <% @messages.each do |inquiry_message| %>
 <div class="message" data-session="<%= session[:user_id] %>">

  <% if current_user == nil %>
    <% login_user = current_admin %>
  <% else %>
    <% login_user = current_user %>
  <% end %>

    <% if current_user %>
      <% inquiry_message.adminflag = inquiry_message.adminflag == 1? 0:1 %>
    <% end %>

		  <% if inquiry_message.adminflag == 1 %>
		    <div class="message_right" style="margin: 20px 0 20px 0;width: 100%;" >
          <span class="message__right" id="" style="" ><%= inquiry_message.content%></span>
        </div>
      <% else %>
        <div class="message_left" style="margin: 20px 0 20px 0;width: 100%;" >
          <span class="message__left" id="" style="" ><%= inquiry_message.content%></span>
        </div>
		  <% end %>

 <% end %>
 </div>

app/views/inquiry_messages/_inquiry_message_form.html.erb
<form class="message_form" padding-top="50px;">

  <input type="hidden" name="inquiry_room_id" value="<%= inquiry_room_id %>">
  <% if admin_signed_in? %>
	  <input type="hidden" name="adminflag" id="adminflag" value="1">
  <% else %>
	  <input type="hidden" name="adminflag" id="adminflag" value="0">
 <% end %>

  <div class="block-center">
	  <input class="input-text" type="text" name="content" placeholder="Aa" data-behavior="chat_speaker" style="height: 50px;width: 650px;">
	  <button id="send_inquiry" type="button" name="test" data-behavior="test" style="height: 45px;width: 45px;color: #777;">
	  	<i class="fas fa-location-arrow"></i>
	  </button>
  </div>

</form>